services:
  
  usersdb:
    environment:
      MSSQL_SA_PASSWORD: "password123!"
      ACCEPT_EULA: "Y"
    restart: always
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$${MSSQL_SA_PASSWORD}" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    ports:
      - "1433:1433"
    
  infrastructure-identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:5001
    depends_on: 
      usersdb:
        condition: service_healthy
    ports:
      - "5001:5001"
      
  usermanagement-webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:5002
    depends_on: 
      - infrastructure-identity
    ports:
      - "5002:5002"

  notes-webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:5003
    depends_on: 
      - infrastructure-identity
      - usermanagement-webapi
    ports:
      - "5003:5003"
